FROM node:18-alpine3.15 as build

RUN apk add --no-cache protoc

WORKDIR /app

ENV protoc_gen_grpc_web=./node_modules/.bin/protoc-gen-grpc-web

COPY ./frontend/package.json .
COPY ./frontend/package-lock.json .
COPY ./proto/greeting.proto .

RUN npm install

RUN mkdir -p ./src/proto
RUN protoc -I=. greeting.proto \
  --plugin=protoc-gen-grpc-web=${protoc_gen_grpc_web} \
  --js_out=import_style=commonjs:./src \
  --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./src

COPY ./frontend .

EXPOSE 8081

CMD ["npm", "start"]