FROM node:16.14.2-alpine3.15

WORKDIR /app

COPY ./backend/package.json .
COPY ./backend/package-lock.json .

RUN npm install

COPY ./proto/greeting.proto .
COPY ./backend/ .

CMD [ "node", "server.js" ]