version: "3"

services:
  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    env_file: "./frontend/.env"
    ports:
      - "8081:8081"
    depends_on:
      - envoy-proxy-service
      - backend-service

  backend-service:
    build:
      context: .
      dockerfile: Dockerfile-backend
    env_file: "./backend/.env"
    ports:
      - "50051:50051"

  envoy-proxy-service:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8000:8000"
